:toc:

https://vuejs.org/guide/introduction.html

== Basis-Setup

[soure,bash]
----
npm create vue@3.10.3 # https://vuejs.org/guide/quick-start.html
# ✔ Project name: … vue-guide
# ✔ Add TypeScript? … No / Yes
# ✔ Add JSX Support? … No / Yes
# ✔ Add Vue Router for Single Page Application development? … No / Yes
# ✔ Add Pinia for state management? … No / Yes
# ✔ Add Vitest for Unit Testing? … No / Yes
# ✔ Add an End-to-End Testing Solution? › Playwright
# ✔ Add ESLint for code quality? … No / Yes
# ✔ Add Prettier for code formatting? … No / Yes
# ✔ Add Vue DevTools 7 extension for debugging? (experimental) … No / Yes

cd vue-guide
npm install
npm run format
npm run dev
----

== Definitionen


Composition API::

Go with Composition API + Single-File Components if you plan to build full applications with Vue.
[source,vue]
----
<script setup>
import { ref, onMounted } from 'vue'

// reactive state
const count = ref(0)

// functions that mutate state and trigger updates
function increment() {
  count.value++
}

// lifecycle hooks
onMounted(() => {
  console.log(`The initial count is ${count.value}.`)
})
</script>

<template>
  <button @click="increment">Count is: {{ count }}</button>
</template>
----

Directive::
Directives sind immer mit `v-` geprefixed

Options API::

Go with Options API if you are not using build tools, or plan to use Vue primarily in low-complexity scenarios, e.g. progressive enhancement.
[source,vue]
----
<script>
export default {
  // Properties returned from data() become reactive state
  // and will be exposed on `this`.
  data() {
    return {
      count: 0
    }
  },

  // Methods are functions that mutate state and trigger updates.
  // They can be bound as event handlers in templates.
  methods: {
    increment() {
      this.count++
    }
  },

  // Lifecycle hooks are called at different stages
  // of a component's lifecycle.
  // This function will be called when the component is mounted.
  mounted() {
    console.log(`The initial count is ${this.count}.`)
  }
}
</script>

<template>
  <button @click="increment">Count is: {{ count }}</button>
</template>
----

SFC:: SingleFileComponents -> *.vue


== Standalone vue

kann man machen -> siehe link:standalone[standalone].

== Template Syntax

https://vuejs.org/guide/essentials/template-syntax.html

Text Interpoliation::
[source,html]
----
<span>Message: {{ msg }}</span>
----

Raw HTML::
v-html Direktive nutzen
[source,html]
----
<p>Using text interpolation: {{ rawHtml }}</p>
<p>Using v-html directive: <span v-html="rawHtml"></span></p>
----

Attribute Bindings::
Um Attribute zu setzen `v-bind` nutzen
[source,html]
----
<div v-bind:id="dynamicId"></div>
<!-- Kurzschreibweise -->
<div :id="dynamicId"></div>
<!-- Ab vue 3.4 -->
<!-- same as :id="id" -->
<div :id></div>
----

JavaScriptExpressions::
Können in allen interpoliation (mustaches) verwendet werden.
Und in allen Attribt-Directiven (v-...)
[source,html]
----
{{ number + 1 }}

{{ ok ? 'YES' : 'NO' }}

{{ message.split('').reverse().join('') }}

<div :id="`list-${id}`"></div>

<!-- nicht erlaubt!!!! -->
<!-- this is a statement, not an expression: -->
{{ var a = 1 }}
<!-- flow control won't work either, use ternary expressions -->
{{ if (ok) { return message } }}
----

Calling Functions::
component-exposed Methoden können in allen bindings aufgerufen werden.
Werden auf jedem Update aufgerufen,
sollten also keine Seiteneffekte haben.
[source,html]
----
<time :title="toTitleDate(date)" :datetime="date">
  {{ formatDate(date) }}
</time>

<!-- shorthand für v-on = @ -->
<a v-on:click="doSomething"> ... </a>
<a @click="doSomething"> ... </a>
----

Dynamic Arguments::
[source,html]
----
<!--
Note that there are some constraints to the argument expression,
as explained in the "Dynamic Argument Value Constraints" and "Dynamic Argument Syntax Constraints" sections below.
-->
<a v-bind:[attributeName]="url"> ... </a>

<!-- shorthand -->
<a :[attributeName]="url"> ... </a>
----

Modifiers::

Bsp:
* v-on:submit.prevent="onSubmit"
** prevent ist Modifier